//! Canonical Vaulted QR payloads.
//!
//! This module defines the signed payload layer shared by Scan-to-Login,
//! Scan-to-Pair-Device, Scan-to-Sign-XRPL-Transaction and
//! Scan-to-Approve-File-Grant.  QR bodies deliberately contain only public or
//! opaque data.  Seed phrases, private keys, file keys, plaintext filenames and
//! plaintext note contents must never be encoded in these payloads.

use ed25519_dalek::{Signature, Signer, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

use crate::{CryptoError, Result, VaultedIdentityKeys};

/// Protocol marker for canonical Vaulted QR payloads.
pub const VAULTED_QR_PROTOCOL: &str = "vaulted-qr-v1";

/// QR intent supported by Vaulted Wallet Mode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VaultedQrIntent {
    /// Desktop login approved by a trusted Vaulted mobile/device identity.
    Login,
    /// Pair a new device with an existing Vaulted identity.
    PairDevice,
    /// Review and sign an XRPL transaction, such as NFTokenMint.
    SignXrplTransaction,
    /// Approve a file grant/key-envelope operation.
    ApproveFileGrant,
}

/// Canonical unsigned QR body.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VaultedQrPayloadBody {
    /// Protocol marker. Must equal [`VAULTED_QR_PROTOCOL`].
    pub protocol: String,
    /// Payload intent.
    pub intent: VaultedQrIntent,
    /// Unique request id generated by desktop/oracle.
    pub request_id: String,
    /// One-time anti-replay challenge, hex/base64/opaque string.
    pub challenge: String,
    /// Oracle/public service URL expected by the scanner.
    pub oracle_url: String,
    /// RFC3339 timestamp after which the request must be rejected.
    pub expires_at: String,
    /// Optional identity expected to approve/sign this payload.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_id: Option<String>,
    /// Optional requesting desktop/device id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requester_device_id: Option<String>,
    /// Optional human-readable requesting desktop/device name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requester_device_name: Option<String>,
    /// Optional public key for a device being paired.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_public_key: Option<String>,
    /// Optional XRPL transaction JSON for signing requests.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub xrpl_tx_json: Option<serde_json::Value>,
    /// Optional expected XRPL account that must sign the transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expected_xrpl_account: Option<String>,
    /// Optional Vault object id for grant approvals.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vault_object_id: Option<String>,
    /// Optional grant id for grant approvals.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grant_id: Option<String>,
    /// Optional recipient identity id for grant approvals/device pairing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recipient_identity_id: Option<String>,
    /// Optional permissions for grant approvals.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<String>>,
    /// Human-readable summary shown before approval/signing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub human_summary: Option<String>,
}

impl VaultedQrPayloadBody {
    /// Creates a Scan-to-Login QR body.
    pub fn scan_to_login(
        request_id: impl Into<String>,
        challenge: impl Into<String>,
        oracle_url: impl Into<String>,
        expires_at: impl Into<String>,
        desktop_device_id: Option<String>,
        desktop_device_name: Option<String>,
        desktop_device_public_key: Option<String>,
    ) -> Self {
        Self {
            protocol: VAULTED_QR_PROTOCOL.to_string(),
            intent: VaultedQrIntent::Login,
            request_id: request_id.into(),
            challenge: challenge.into(),
            oracle_url: oracle_url.into(),
            expires_at: expires_at.into(),
            identity_id: None,
            requester_device_id: desktop_device_id,
            requester_device_name: desktop_device_name,
            device_public_key: desktop_device_public_key,
            xrpl_tx_json: None,
            expected_xrpl_account: None,
            vault_object_id: None,
            grant_id: None,
            recipient_identity_id: None,
            permissions: None,
            human_summary: Some("Approve Vaulted desktop login".to_string()),
        }
    }

    /// Creates a Scan-to-Pair-Device QR body.
    pub fn scan_to_pair_device(
        request_id: impl Into<String>,
        challenge: impl Into<String>,
        oracle_url: impl Into<String>,
        expires_at: impl Into<String>,
        identity_id: impl Into<String>,
        device_public_key: impl Into<String>,
        device_name: Option<String>,
    ) -> Self {
        Self {
            protocol: VAULTED_QR_PROTOCOL.to_string(),
            intent: VaultedQrIntent::PairDevice,
            request_id: request_id.into(),
            challenge: challenge.into(),
            oracle_url: oracle_url.into(),
            expires_at: expires_at.into(),
            identity_id: Some(identity_id.into()),
            requester_device_id: None,
            requester_device_name: device_name,
            device_public_key: Some(device_public_key.into()),
            xrpl_tx_json: None,
            expected_xrpl_account: None,
            vault_object_id: None,
            grant_id: None,
            recipient_identity_id: None,
            permissions: None,
            human_summary: Some("Pair a new Vaulted device".to_string()),
        }
    }

    /// Creates a Scan-to-Sign-XRPL-Transaction QR body.
    pub fn scan_to_sign_xrpl_transaction(
        request_id: impl Into<String>,
        challenge: impl Into<String>,
        oracle_url: impl Into<String>,
        expires_at: impl Into<String>,
        tx_json: serde_json::Value,
        expected_xrpl_account: impl Into<String>,
        human_summary: Option<String>,
    ) -> Self {
        Self {
            protocol: VAULTED_QR_PROTOCOL.to_string(),
            intent: VaultedQrIntent::SignXrplTransaction,
            request_id: request_id.into(),
            challenge: challenge.into(),
            oracle_url: oracle_url.into(),
            expires_at: expires_at.into(),
            identity_id: None,
            requester_device_id: None,
            requester_device_name: None,
            device_public_key: None,
            xrpl_tx_json: Some(tx_json),
            expected_xrpl_account: Some(expected_xrpl_account.into()),
            vault_object_id: None,
            grant_id: None,
            recipient_identity_id: None,
            permissions: None,
            human_summary,
        }
    }

    /// Creates a Scan-to-Approve-File-Grant QR body.
    pub fn scan_to_approve_file_grant(
        request_id: impl Into<String>,
        challenge: impl Into<String>,
        oracle_url: impl Into<String>,
        expires_at: impl Into<String>,
        vault_object_id: impl Into<String>,
        grant_id: impl Into<String>,
        recipient_identity_id: impl Into<String>,
        permissions: Vec<String>,
    ) -> Self {
        Self {
            protocol: VAULTED_QR_PROTOCOL.to_string(),
            intent: VaultedQrIntent::ApproveFileGrant,
            request_id: request_id.into(),
            challenge: challenge.into(),
            oracle_url: oracle_url.into(),
            expires_at: expires_at.into(),
            identity_id: None,
            requester_device_id: None,
            requester_device_name: None,
            device_public_key: None,
            xrpl_tx_json: None,
            expected_xrpl_account: None,
            vault_object_id: Some(vault_object_id.into()),
            grant_id: Some(grant_id.into()),
            recipient_identity_id: Some(recipient_identity_id.into()),
            permissions: Some(permissions),
            human_summary: Some("Approve encrypted file grant".to_string()),
        }
    }

    /// Validates structural fields and intent-specific required fields.
    pub fn validate(&self) -> Result<()> {
        if self.protocol != VAULTED_QR_PROTOCOL {
            return Err(CryptoError::InvalidData(
                "Unsupported QR protocol".to_string(),
            ));
        }
        if self.request_id.trim().is_empty()
            || self.challenge.trim().is_empty()
            || self.oracle_url.trim().is_empty()
            || self.expires_at.trim().is_empty()
        {
            return Err(CryptoError::InvalidData(
                "QR payload is missing required fields".to_string(),
            ));
        }

        match self.intent {
            VaultedQrIntent::Login => Ok(()),
            VaultedQrIntent::PairDevice => {
                require_some(&self.identity_id, "identity_id")?;
                require_some(&self.device_public_key, "device_public_key")
            },
            VaultedQrIntent::SignXrplTransaction => {
                require_some(&self.xrpl_tx_json, "xrpl_tx_json")?;
                require_some(&self.expected_xrpl_account, "expected_xrpl_account")
            },
            VaultedQrIntent::ApproveFileGrant => {
                require_some(&self.vault_object_id, "vault_object_id")?;
                require_some(&self.grant_id, "grant_id")?;
                require_some(&self.recipient_identity_id, "recipient_identity_id")?;
                let permissions = self.permissions.as_ref().ok_or_else(|| {
                    CryptoError::InvalidData("QR payload missing permissions".to_string())
                })?;
                if permissions.is_empty() {
                    return Err(CryptoError::InvalidData(
                        "QR grant payload must include at least one permission".to_string(),
                    ));
                }
                Ok(())
            },
        }
    }

    /// Serializes this body into the canonical bytes used for Ed25519 signatures.
    pub fn canonical_signing_bytes(&self) -> Result<Vec<u8>> {
        self.validate()?;
        let mut out = b"Vaulted QR Payload v1\n".to_vec();
        out.extend(
            serde_json::to_vec(self).map_err(|e| CryptoError::Serialization(e.to_string()))?,
        );
        Ok(out)
    }
}

/// Signed canonical QR payload.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VaultedSignedQrPayload {
    /// Unsigned canonical body.
    pub body: VaultedQrPayloadBody,
    /// Vaulted identity id of the signer.
    pub signer_identity_id: String,
    /// Ed25519 signing public key, hex encoded.
    pub signer_public_key: String,
    /// Ed25519 signature over [`VaultedQrPayloadBody::canonical_signing_bytes`], hex encoded.
    pub signature: String,
}

impl VaultedSignedQrPayload {
    /// Signs a QR payload with the Vaulted identity signing key.
    pub fn sign(body: VaultedQrPayloadBody, identity: &VaultedIdentityKeys) -> Result<Self> {
        body.validate()?;
        let signing_key = identity.signing_key();
        let bytes = body.canonical_signing_bytes()?;
        let signature = signing_key.sign(&bytes);
        Ok(Self {
            body,
            signer_identity_id: identity.identity_id_hex(),
            signer_public_key: identity.signing_public_key_hex(),
            signature: hex::encode(signature.to_bytes()),
        })
    }

    /// Verifies the Ed25519 QR payload signature and structural fields.
    pub fn verify(&self) -> Result<()> {
        self.body.validate()?;
        let public_key = hex::decode(&self.signer_public_key)
            .map_err(|_| CryptoError::InvalidData("Invalid QR signer public key".to_string()))?;
        if public_key.len() != 32 {
            return Err(CryptoError::InvalidData(
                "Invalid QR signer public key length".to_string(),
            ));
        }
        let mut public_key_bytes = [0u8; 32];
        public_key_bytes.copy_from_slice(&public_key);
        let verifying_key = VerifyingKey::from_bytes(&public_key_bytes)
            .map_err(|_| CryptoError::InvalidData("Invalid QR signer public key".to_string()))?;

        let signature = hex::decode(&self.signature)
            .map_err(|_| CryptoError::InvalidData("Invalid QR signature".to_string()))?;
        if signature.len() != 64 {
            return Err(CryptoError::InvalidData(
                "Invalid QR signature length".to_string(),
            ));
        }
        let mut signature_bytes = [0u8; 64];
        signature_bytes.copy_from_slice(&signature);
        let signature = Signature::from_bytes(&signature_bytes);
        verifying_key
            .verify(&self.body.canonical_signing_bytes()?, &signature)
            .map_err(|_| CryptoError::SignatureVerification)
    }

    /// Serializes the signed payload as compact JSON suitable for QR encoding.
    pub fn to_qr_json(&self) -> Result<String> {
        serde_json::to_string(self).map_err(|e| CryptoError::Serialization(e.to_string()))
    }

    /// Parses and verifies a compact QR JSON payload.
    pub fn from_qr_json_verified(input: &str) -> Result<Self> {
        let payload: Self =
            serde_json::from_str(input).map_err(|e| CryptoError::Deserialization(e.to_string()))?;
        payload.verify()?;
        Ok(payload)
    }
}

fn require_some<T>(value: &Option<T>, name: &str) -> Result<()> {
    if value.is_some() {
        Ok(())
    } else {
        Err(CryptoError::InvalidData(format!(
            "QR payload missing {name}"
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::seed::{SeedManager, DEFAULT_MNEMONIC_WORDS};

    fn identity() -> VaultedIdentityKeys {
        let mnemonic = SeedManager::generate_mnemonic(DEFAULT_MNEMONIC_WORDS).unwrap();
        VaultedIdentityKeys::from_mnemonic(&mnemonic, None).unwrap()
    }

    #[test]
    fn signs_and_verifies_scan_to_login_payload() {
        let identity = identity();
        let body = VaultedQrPayloadBody::scan_to_login(
            "login-1",
            "challenge-1",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            Some("desktop-1".to_string()),
            Some("Desktop".to_string()),
            Some("device-pk".to_string()),
        );

        let signed = VaultedSignedQrPayload::sign(body, &identity).unwrap();
        signed.verify().unwrap();
        assert_eq!(signed.body.intent, VaultedQrIntent::Login);
    }

    #[test]
    fn supports_all_priority_four_qr_modes() {
        let identity = identity();
        let login = VaultedQrPayloadBody::scan_to_login(
            "login-1",
            "challenge-1",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            None,
            None,
            None,
        );
        let pair = VaultedQrPayloadBody::scan_to_pair_device(
            "pair-1",
            "challenge-2",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            identity.identity_id_hex(),
            identity.device_public_key_hex(),
            Some("Laptop".to_string()),
        );
        let sign = VaultedQrPayloadBody::scan_to_sign_xrpl_transaction(
            "sign-1",
            "challenge-3",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            serde_json::json!({"TransactionType":"NFTokenMint","Account":"rEXAMPLE"}),
            "rEXAMPLE",
            Some("Mint Vaulted NFT".to_string()),
        );
        let grant = VaultedQrPayloadBody::scan_to_approve_file_grant(
            "grant-1",
            "challenge-4",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            "vault-1",
            "grant-1",
            "recipient-1",
            vec!["read".to_string()],
        );

        for body in [login, pair, sign, grant] {
            let signed = VaultedSignedQrPayload::sign(body, &identity).unwrap();
            signed.verify().unwrap();
        }
    }

    #[test]
    fn tampered_payload_fails_verification() {
        let identity = identity();
        let body = VaultedQrPayloadBody::scan_to_login(
            "login-1",
            "challenge-1",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            None,
            None,
            None,
        );
        let mut signed = VaultedSignedQrPayload::sign(body, &identity).unwrap();
        signed.body.challenge = "tampered".to_string();
        assert!(signed.verify().is_err());
    }

    #[test]
    fn compact_qr_json_roundtrips_and_verifies() {
        let identity = identity();
        let body = VaultedQrPayloadBody::scan_to_approve_file_grant(
            "grant-1",
            "challenge-4",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            "vault-1",
            "grant-1",
            "recipient-1",
            vec!["read".to_string()],
        );
        let signed = VaultedSignedQrPayload::sign(body, &identity).unwrap();
        let json = signed.to_qr_json().unwrap();
        let parsed = VaultedSignedQrPayload::from_qr_json_verified(&json).unwrap();
        assert_eq!(parsed, signed);
    }

    #[test]
    fn intent_specific_required_fields_are_enforced() {
        let mut body = VaultedQrPayloadBody::scan_to_approve_file_grant(
            "grant-1",
            "challenge-4",
            "https://oracle.example",
            "2026-05-13T12:00:00Z",
            "vault-1",
            "grant-1",
            "recipient-1",
            vec!["read".to_string()],
        );
        body.permissions = Some(vec![]);
        assert!(body.validate().is_err());
    }
}
